name: Smart Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: ravimude20/smartReviewer@main
        with:
          GITHUB_TOKEN: "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"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
